version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/api-spec-exposer/" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: deps:"
    labels:
      - "dependencies"
      - "go"
